Small Updates to Sidenav
Copilot-CRM/frontend-monolith pull request #6
Opened 2024-09-23 23:42 UTC by plhnk

starting a PR for minor visual tweaks as I familiarize myself w/repo 
- improve legibility on nav items --> style icons separately from text
- add transitions on hovers for nav items
- align border for nested items to horizontal center of icon

2024-09-27 14:34 UTC, rttnbrgr requested changes
Added my notes.

### Couple follow up things:

- Would love to get any changes we make, into figma as well. If iterating in code is faster for you, I'm good with that, let's just make sure changes get unified.  
- Feel free to use the main repo. I'm not sure the exact benefit or drawbacks of using a fork, but please do not feel restricted from hopping into the main repo. 

Awesome to see you digging into to all this @plhnk

2024-09-27 14:34 UTC, rttnbrgr commented on src/components/sidenav/sidenav.tsx
> +const _liHover = `cursor-pointer hover:bg-blue-500 hover:text-white transition-colors duration-300`;
These changes ripple out to the client portal nav as well.

Take a look at how it's affected those styles and let's see how to best address that.

2024-09-27 14:34 UTC, rttnbrgr commented on src/components/sidenav/sidenav.tsx
> +      )}
Is this adding a slight color variation between the icon and the nav text? @plhnk

2024-09-27 14:34 UTC, rttnbrgr commented on src/components/sidenav/sidenav.tsx
> +          setExpanded((cv) => !cv);
this seems like its prettier differences? May want to pull in the latest from main as we now have a `.prettierrc` in the repo

2024-09-27 14:34 UTC, rttnbrgr commented on src/components/sidenav/sidenav.tsx
> +                onClick={(e) => {
ditto the above

2024-10-14 14:31 UTC, plhnk commented
closing out as hardcoding color values clashes with the other sidebars - will pick any refinements after semantic color layer is in place

2024-10-14 14:31 UTC, closed without merging